# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='name',
            field=models.CharField(db_index=True, default='Droker', max_length=100),
            preserve_default=False,
        ),
    ]
