# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 16:04
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_reporter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='stories_annormalies',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
